### PR TITLE
tweak(database/rawTransaction): actually throw an error when a transaction fails.

### PR DESCRIPTION
**Pull request by slashkeyvalue**
Had the need to catch errors while working with transactions and for some reason it was logging them instead of actually throwing them:?

### CODE REVIEW

**Comment by thelindat** [comment]
It’s already throwing an error, that’s what is being caught and logged?

**Comment by slashkeyvalue** [comment]
yes, it's being logged instead of throwing the error and letting the user deal with whatever happened.

**Comment by thelindat** [comment]
And then tell the Lua runtime to get fucked if they want to do something when a transaction fails because you can't catch it?

**Comment by thelindat** [comment]
Closing this. Making this change would be _breaking_, and while it can be worked around it just cannot be justified in any way. Besides, I've already decided that this resources basically has to be as close to 100% compatible with mysql-async to avoid the stress of dealing with the FiveM "community".

**Pull request closed without merging**
