### PR TITLE
Refactor MySQL readiness check and remove unused imports & Add Cache class and definition

### PR DESCRIPTION
**Pull request by Purpose-Dev**
This pull request simplifies MySQL readiness checking and cleans up unused imports for improved code clarity and maintainability. It also introduces a CacheValue type and a Cache class for potential query caching, enhancing performance.

### CODE REVIEW

**Comment by darksaid98** [comment]
I assume this is a caching system for return values instead of just caching the query string like `mysql2` does (*just based on my reading of the code*). How would such a feature be exposed to users?

I'd recommend turning this into a draft for the maintainers, as right now the cache part of this is technically just dead code (*and a feature I'm not certain the maintainers want to maintain/add*).

**Comment by Purpose-Dev** [comment]
> I assume this is a caching system for return values instead of just caching the query string like `mysql2` does (_just based on my reading of the code_). How would such a feature be exposed to users?
> 
> I'd recommend turning this into a draft for the maintainers, as right now the cache part of this is technically just dead code (_and a feature I'm not certain the maintainers want to maintain/add_).

Yes, it's a cache system for return values. Working a lot with the cloud, you have to save where you can, and making a request when a value hasn't changed is inconceivable. The user wouldn't have to use the cache or modify his code, because the aim is that, with a query like MySQL.fetch, he'd face it in the background.

**Comment by thelindat** [comment]
This PR is all over the place, making changes to different and unrelated parts of the code; please keep the scope of PRs limited to a single issue.

- Dynamic connection limit
Not necessarily a bad idea, but too many connections may increase the chances of deadlocks (another issue to look into preventing) and I'd probably want a min-max range for the default.

- buildFlags
Not much difference having it inline or as part of a new function, but changing the default flags simply isn't an option. Aside from compatibility concerns, multi-statements are a huge security risk; it's also already possible using `multipleStatements=true` in the connection string (along with `compress=true`).

- Cache
As already pointed out, you've created some dead-code and it isn't something I particularly want to maintain. While you're right that it's good practice to try and cache query results and eliminate unnecessary i/o (especially for remote databases), we also can't know when the data has changed or how long the result should be stored.

There's already some caching done by the driver for table data, and a lot of work has gone into databases for improving query planning, caching results, indexing, etc. It makes more sense to rely on those systems and leave further optimisation to users, imo. Any sort of cache would need to be optional, have a short lifespan, and require some new functions to utilise instead of the default.


Other changes are otherwise frivolous and provide no real value.

**Comment by Purpose-Dev** [comment]
> This PR is all over the place, making changes to different and unrelated parts of the code; please keep the scope of PRs limited to a single issue.
> 
> * Dynamic connection limit
>   Not necessarily a bad idea, but too many connections may increase the chances of deadlocks (another issue to look into preventing) and I'd probably want a min-max range for the default.
> * buildFlags
>   Not much difference having it inline or as part of a new function, but changing the default flags simply isn't an option. Aside from compatibility concerns, multi-statements are a huge security risk; it's also already possible using `multipleStatements=true` in the connection string (along with `compress=true`).
> * Cache
>   As already pointed out, you've created some dead-code and it isn't something I particularly want to maintain. While you're right that it's good practice to try and cache query results and eliminate unnecessary i/o (especially for remote databases), we also can't know when the data has changed or how long the result should be stored.
>   There's already some caching done by the driver for table data, and a lot of work has gone into databases for improving query planning, caching results, indexing, etc. It makes more sense to rely on those systems and leave further optimisation to users, imo. Any sort of cache would need to be optional, have a short lifespan, and require some new functions to utilise instead of the default.
> 
> Other changes are otherwise frivolous and provide no real value.

Thank you for the thorough review. I’ll address each point in detail and outline my approach moving forward:

### **PR Scope**  
You're absolutely right about the need for focused PRs. Combining unrelated changes here was an oversight, and I’ll break this PR into smaller, more focused pieces, each addressing a specific issue or enhancement. This will make reviews more efficient and align better with development best practices.

---

### **Dynamic Connection Limit**  
The dynamic connection limit proposal indeed warrants more consideration. While increasing the limit dynamically can improve throughput in some scenarios, you correctly point out the risks of deadlocks. To address this:

1. **Min-Max Range**: I will add a configurable minimum and maximum range to ensure that connection growth remains within predictable and manageable bounds.
2. **Deadlock Prevention**: I’ll investigate whether we can implement safeguards such as:
   - A timeout or circuit-breaker pattern for stuck connections.
   - Detecting and logging potential deadlock scenarios for further analysis.
3. **Documentation**: I’ll also include documentation detailing the potential trade-offs and best practices for configuring connection limits.

---

### **`buildFlags`**  
On the changes to `buildFlags`:
1. **Security Concerns**: I fully agree that enabling multi-statements by default is unacceptable due to the inherent security risks, including SQL injection vulnerabilities. I’ll revert this change entirely.
2. **Function Extraction**: While the inline-to-function change is not critical, it can improve readability and reusability. I’ll retain the function extraction but ensure it preserves the existing behavior and compatibility.
3. **User Control**: For users requiring multi-statement support, I’ll add better documentation around enabling `multipleStatements=true` and possibly a warning about its associated risks.

---

### **Cache Implementation**  
Your feedback on caching is well-taken. Here’s how I’ll proceed:
1. **Remove Dead Code**: I’ll eliminate the current caching implementation from this PR.
2. **Future Considerations**:
   - **Optionality**: Any caching would need to be entirely optional, configurable, and disabled by default.
   - **Consistency Guarantees**: Caching must account for data staleness and invalidation policies. Without reliable mechanisms (e.g., cache-busting events), we risk introducing hard-to-diagnose issues.
   - **Database-Driven Optimizations**: I agree that leveraging the database’s native capabilities (e.g., query planning, internal caching, indexing) is often the better approach. However, if a specific use case arises where application-layer caching is warranted, I’d propose using a dedicated caching library (e.g., Redis) and carefully scoping its usage.

---

### **Other Changes**  
I’ll revisit the other changes and ensure that only meaningful, value-added modifications remain. Any superficial or stylistic adjustments will be removed to maintain focus.

---

I’ll prioritize splitting the PR and addressing these changes in a structured way. Your insights have clarified the architectural considerations, and I’ll ensure future submissions are more focused and aligned with the project’s direction. Let me know if you have additional thoughts or preferences before I proceed.

**Pull request closed without merging**
